# Generated by Django 5.2.7 on 2025-10-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_remove_donacion_metodo_remove_donacion_tipo_and_more'),
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donaciones', to='adopciones.tipomascota'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
