# Generated by Django 5.2.7 on 2025-10-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='MetodoDonacion',
        ),
        migrations.DeleteModel(
            name='Donacion',
        ),
    ]
